<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShopBundle\Controller\Admin\Sell\Catalog\AttachmentController' shared service.

$this->services['PrestaShopBundle\\Controller\\Admin\\Sell\\Catalog\\AttachmentController'] = $instance = new \PrestaShopBundle\Controller\Admin\Sell\Catalog\AttachmentController();

$instance->setContainer($this);

return $instance;
