<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\PrestaShop\Adapter\Attachment\AttachmentRepository' shared service.

return $this->services['PrestaShop\\PrestaShop\\Adapter\\Attachment\\AttachmentRepository'] = new \PrestaShop\PrestaShop\Adapter\Attachment\AttachmentRepository(($this->services['doctrine.dbal.default_connection'] ?? $this->getDoctrine_Dbal_DefaultConnectionService()), 'ps_');
