<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\PrestaShop\Adapter\Product\CommandHandler\AssignProductToCategoryHandler' shared autowired service.

return $this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\CommandHandler\\AssignProductToCategoryHandler'] = new \PrestaShop\PrestaShop\Adapter\Product\CommandHandler\AssignProductToCategoryHandler(($this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Repository\\ProductRepository'] ?? $this->load('getProductRepositoryService.php')));
