<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_platform.openapi.command' shared service.

$this->privates['api_platform.openapi.command'] = $instance = new \ApiPlatform\Symfony\Bundle\Command\OpenApiCommand(($this->privates['api_platform.openapi.factory.next'] ?? $this->load('getApiPlatform_Openapi_Factory_NextService.php')), ($this->services['serializer'] ?? $this->getSerializerService()));

$instance->setName('api:openapi:export');

return $instance;
