<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_platform.listener.view.respond' shared service.

return $this->privates['api_platform.listener.view.respond'] = new \ApiPlatform\Symfony\EventListener\RespondListener(($this->privates['api_platform.metadata.resource.metadata_collection_factory.cached'] ?? $this->getApiPlatform_Metadata_Resource_MetadataCollectionFactory_CachedService()), ($this->privates['api_platform.symfony.iri_converter'] ?? $this->getApiPlatform_Symfony_IriConverterService()));
