<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\PrestaShop\Adapter\Product\AdminProductWrapper' shared service.

@trigger_error('The "PrestaShop\\PrestaShop\\Adapter\\Product\\AdminProductWrapper" service is deprecated. You should stop using it, as it will be removed in the future.', E_USER_DEPRECATED);

return $this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\AdminProductWrapper'] = new \PrestaShop\PrestaShop\Adapter\Product\AdminProductWrapper(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getContext()->employee->getAssociatedShops(), ($this->services['prestashop.core.localization.locale.context_locale'] ?? $this->load('getPrestashop_Core_Localization_Locale_ContextLocaleService.php')), ($this->services['PrestaShopBundle\\Utils\\FloatParser'] ?? $this->load('getFloatParserService.php')));
