<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\PrestaShop\Adapter\Product\Update\Filler\BasicInformationFiller' shared service.

return $this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Update\\Filler\\BasicInformationFiller'] = new \PrestaShop\PrestaShop\Adapter\Product\Update\Filler\BasicInformationFiller(($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration()))->get("PS_LANG_DEFAULT"));
