<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\PrestaShop\Adapter\Category\Repository\CategoryPreviewRepository' shared service.

return $this->services['PrestaShop\\PrestaShop\\Adapter\\Category\\Repository\\CategoryPreviewRepository'] = new \PrestaShop\PrestaShop\Adapter\Category\Repository\CategoryPreviewRepository(($this->services['PrestaShop\\PrestaShop\\Adapter\\Category\\Repository\\CategoryRepository'] ?? $this->load('getCategoryRepositoryService.php')), ($this->services['prestashop.adapter.image.category_image_path_factory'] ?? $this->load('getPrestashop_Adapter_Image_CategoryImagePathFactoryService.php')));
