<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShopBundle\Controller\Admin\Improve\International\CountryController' shared service.

$this->services['PrestaShopBundle\\Controller\\Admin\\Improve\\International\\CountryController'] = $instance = new \PrestaShopBundle\Controller\Admin\Improve\International\CountryController();

$instance->setContainer($this);

return $instance;
