<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\PrestaShop\Core\Product\Combination\NameBuilder\CombinationNameBuilderInterface' shared service.

return $this->services['PrestaShop\\PrestaShop\\Core\\Product\\Combination\\NameBuilder\\CombinationNameBuilderInterface'] = new \PrestaShop\PrestaShop\Core\Product\Combination\NameBuilder\CombinationNameBuilder(($this->services['translator'] ?? $this->getTranslatorService()), ', ', ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration()))->get("PS_ATTRIBUTE_ANCHOR_SEPARATOR"));
