<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\PrestaShop\Core\Util\ColorBrightnessCalculator' shared autowired service.

return $this->services['PrestaShop\\PrestaShop\\Core\\Util\\ColorBrightnessCalculator'] = new \PrestaShop\PrestaShop\Core\Util\ColorBrightnessCalculator();
