<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShopBundle\Command\DebugCommand' shared service.

return $this->services['PrestaShopBundle\\Command\\DebugCommand'] = new \PrestaShopBundle\Command\DebugCommand(($this->services['prestashop.core.command_bus'] ?? $this->load('getPrestashop_Core_CommandBusService.php')), ($this->services['prestashop.adapter.debug_mode'] ?? ($this->services['prestashop.adapter.debug_mode'] = new \PrestaShop\PrestaShop\Adapter\Debug\DebugMode())));
