<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Sell\Product\Details\DetailsType' shared service.

return $this->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Product\\Details\\DetailsType'] = new \PrestaShopBundle\Form\Admin\Sell\Product\Details\DetailsType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getLanguages(), ($this->services['prestashop.core.form.choice_provider.product_condition_choice_provider'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_ProductConditionChoiceProviderService.php')), ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration()))->getBoolean("PS_FEATURE_FEATURE_ACTIVE"));
