<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.sell.product.toolbar_buttons_provider' shared service.

return $this->services['form.type.sell.product.toolbar_buttons_provider'] = new \PrestaShopBundle\Form\Toolbar\ProductToolbarButtonsProvider(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['prestashop.router'] ?? $this->load('getPrestashop_RouterService.php')), ($this->services['prestashop.adapter.shop.url.help_provider'] ?? $this->load('getPrestashop_Adapter_Shop_Url_HelpProviderService.php')), ($this->services['prestashop.adapter.data_provider.module'] ?? $this->getPrestashop_Adapter_DataProvider_ModuleService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService()));
