<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.translations.modify' shared service.

return $this->services['form.type.translations.modify'] = new \PrestaShopBundle\Form\Admin\Improve\International\Translations\ModifyTranslationsType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getLanguages(), ($this->services['prestashop.core.form.choice_provider.translation_type'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_TranslationTypeService.php'))->getChoices(), ($this->services['prestashop.core.form.choice_provider.email_content_type'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_EmailContentTypeService.php'))->getChoices(), ($this->services['prestashop.core.form.choice_provider.theme_by_name'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_ThemeByNameService.php'))->getChoices(), ($this->services['prestashop.core.form.choice_provider.module_by_name'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_ModuleByNameService.php'))->getChoices());
