<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.sell.product.description.manufacturer_type' shared service.

return $this->services['form.type.sell.product.description.manufacturer_type'] = new \PrestaShopBundle\Form\Admin\Sell\Product\Description\ManufacturerType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['prestashop.adapter.form.choice_provider.manufacturer_name_by_id'] ?? $this->load('getPrestashop_Adapter_Form_ChoiceProvider_ManufacturerNameByIdService.php')));
