<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.sell.product.options.suppliers_type' shared service.

return $this->services['form.type.sell.product.options.suppliers_type'] = new \PrestaShopBundle\Form\Admin\Sell\Product\Options\SuppliersType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getLanguages(), ($this->services['prestashop.adapter.form.choice_provider.supplier_name_by_id_choice_provider'] ?? ($this->services['prestashop.adapter.form.choice_provider.supplier_name_by_id_choice_provider'] = new \PrestaShop\PrestaShop\Adapter\Form\ChoiceProvider\SupplierNameByIdChoiceProvider())));
