<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.currency_exchange_rate' shared service.

return $this->services['form.type.currency_exchange_rate'] = new \PrestaShopBundle\Form\Admin\Improve\International\Currencies\CurrencyExchangeRateType();
