<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShopBundle\Form\Admin\Type\FormattedTextareaType' shared service.

return $this->services['PrestaShopBundle\\Form\\Admin\\Type\\FormattedTextareaType'] = new \PrestaShopBundle\Form\Admin\Type\FormattedTextareaType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getLanguages());
