<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.customer.required_fields' shared service.

return $this->services['form.type.customer.required_fields'] = new \PrestaShopBundle\Form\Admin\Sell\Customer\RequiredFieldsType(($this->services['prestashop.core.form.choice_provider.customer_required_fields'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_CustomerRequiredFieldsService.php'))->getChoices());
