<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Admin\Sell\Product\Details\FeatureValueType' shared autowired service.

$a = ($this->services['translator'] ?? $this->getTranslatorService());

return $this->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Product\\Details\\FeatureValueType'] = new \PrestaShopBundle\Form\Admin\Sell\Product\Details\FeatureValueType($a, ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getLanguages(), ($this->services['prestashop.adapter.form.choice_provider.features_choice_provider'] ?? $this->load('getPrestashop_Adapter_Form_ChoiceProvider_FeaturesChoiceProviderService.php')), new \PrestaShopBundle\Form\Admin\Sell\Product\EventListener\FeatureValueListener(($this->services['prestashop.adapter.form.choice_provider.feature_values_choice_provider'] ?? $this->load('getPrestashop_Adapter_Form_ChoiceProvider_FeatureValuesChoiceProviderService.php')), ($this->services['form.form_cloner'] ?? ($this->services['form.form_cloner'] = new \PrestaShopBundle\Form\FormCloner())), $a));
