<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.extension.hint_text' shared service.

return $this->services['form.extension.hint_text'] = new \PrestaShopBundle\Form\Admin\Extension\HintTextExtension();
