<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.address.required_fields' shared service.

return $this->services['form.type.address.required_fields'] = new \PrestaShopBundle\Form\Admin\Sell\Address\RequiredFieldsAddressType(($this->services['prestashop.core.form.choice_provider.address_required_fields'] ?? ($this->services['prestashop.core.form.choice_provider.address_required_fields'] = new \PrestaShop\PrestaShop\Core\Form\ChoiceProvider\AddressRequiredFieldsChoiceProvider())));
