<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.search_and_reset' shared service.

return $this->services['form.type.search_and_reset'] = new \PrestaShopBundle\Form\Admin\Type\SearchAndResetType(($this->services['prestashop.router'] ?? $this->load('getPrestashop_RouterService.php')));
