<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.common.shop_selector' shared service.

return $this->services['form.type.common.shop_selector'] = new \PrestaShopBundle\Form\Admin\Type\ShopSelectorType(($this->services['prestashop.core.admin.shop.repository'] ?? $this->load('getPrestashop_Core_Admin_Shop_RepositoryService.php')), ($this->services['prestashop.core.admin.shop_group.repository'] ?? $this->load('getPrestashop_Core_Admin_ShopGroup_RepositoryService.php'))->findActive(), ($this->services['prestashop.adapter.shop.context'] ?? ($this->services['prestashop.adapter.shop.context'] = new \PrestaShop\PrestaShop\Adapter\Shop\Context()))->getContextShopID());
