<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_js_routing.router_debug_exposed_command' shared service.

$this->privates['fos_js_routing.router_debug_exposed_command'] = $instance = new \FOS\JsRoutingBundle\Command\RouterDebugExposedCommand(($this->services['fos_js_routing.extractor'] ?? $this->load('getFosJsRouting_ExtractorService.php')), ($this->services['prestashop.router'] ?? $this->load('getPrestashop_RouterService.php')));

$instance->setName('fos:js-routing:debug');

return $instance;
