<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShopBundle\Controller\Api\FeatureController' shared service.

$this->services['PrestaShopBundle\\Controller\\Api\\FeatureController'] = $instance = new \PrestaShopBundle\Controller\Api\FeatureController();

$instance->featureAttributeRepository = ($this->services['prestashop.core.api.feature_attribute.repository'] ?? $this->load('getPrestashop_Core_Api_FeatureAttribute_RepositoryService.php'));
$instance->setLogger(($this->services['logger'] ?? $this->getLoggerService()));
$instance->setContainer($this);

return $instance;
