<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.sell.product.pricing.specific_price_priority_type' shared service.

return $this->services['form.type.sell.product.pricing.specific_price_priority_type'] = new \PrestaShopBundle\Form\Admin\Sell\Product\Pricing\SpecificPricePriorityType(($this->services['prestashop.core.form.choice_provider.specific_price_priority_choice_provider'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_SpecificPricePriorityChoiceProviderService.php')));
