<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.sell.product.category.category_tree_selector_type' shared service.

return $this->services['form.type.sell.product.category.category_tree_selector_type'] = new \PrestaShopBundle\Form\Admin\Sell\Product\Category\CategoryTreeSelectorType(($this->services['translator'] ?? $this->getTranslatorService()));
