<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.sell.product.event_listener.categories_listener' shared service.

return $this->services['form.type.sell.product.event_listener.categories_listener'] = new \PrestaShopBundle\Form\Admin\Sell\Product\EventListener\CategoriesListener(($this->services['form.form_cloner'] ?? ($this->services['form.form_cloner'] = new \PrestaShopBundle\Form\FormCloner())));
