<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.common.shop_choice_tree' shared service.

return $this->services['form.type.common.shop_choice_tree'] = new \PrestaShopBundle\Form\Admin\Type\ShopChoiceTreeType(($this->services['prestashop.adapter.form.choice_provider.shop_tree_choice_provider'] ?? ($this->services['prestashop.adapter.form.choice_provider.shop_tree_choice_provider'] = new \PrestaShop\PrestaShop\Adapter\Form\ChoiceProvider\ShopTreeChoiceProvider()))->getChoices(), ($this->services['prestashop.bundle.form.data_transformer.string_array_to_integer_array'] ?? ($this->services['prestashop.bundle.form.data_transformer.string_array_to_integer_array'] = new \PrestaShopBundle\Form\DataTransformer\StringArrayToIntegerArrayDataTransformer())));
