<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\PrestaShop\Adapter\Product\FilterCategoriesRequestPurifier' shared service.

@trigger_error('The "PrestaShop\\PrestaShop\\Adapter\\Product\\FilterCategoriesRequestPurifier" service is deprecated. You should stop using it, as it will be removed in the future.', E_USER_DEPRECATED);

return $this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\FilterCategoriesRequestPurifier'] = new \PrestaShop\PrestaShop\Adapter\Product\FilterCategoriesRequestPurifier();
