<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.order.credit_slip.credit_slip_options' shared service.

return $this->services['form.type.order.credit_slip.credit_slip_options'] = new \PrestaShopBundle\Form\Admin\Sell\Order\CreditSlip\CreditSlipOptionsType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getLanguages());
