<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.shop.traffic_seo.meta.url_schema' shared service.

return $this->services['form.type.shop.traffic_seo.meta.url_schema'] = new \PrestaShopBundle\Form\Admin\Configure\ShopParameters\TrafficSeo\Meta\UrlSchemaType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getLanguages(), ($this->services['prestashop.adapter.data_provider.default_route'] ?? ($this->services['prestashop.adapter.data_provider.default_route'] = new \PrestaShop\PrestaShop\Adapter\Routes\DefaultRouteProvider())));
