<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.common.zone_choice' shared service.

return $this->services['form.type.common.zone_choice'] = new \PrestaShopBundle\Form\Admin\Type\ZoneChoiceType(($this->services['prestashop.core.form.choice_provider.zone_by_id'] ?? ($this->services['prestashop.core.form.choice_provider.zone_by_id'] = new \PrestaShop\PrestaShop\Adapter\Form\ChoiceProvider\ZoneByIdChoiceProvider())));
