<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.translations.copy_language' shared service.

return $this->services['form.type.translations.copy_language'] = new \PrestaShopBundle\Form\Admin\Improve\International\Translations\CopyLanguageType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getLanguages(), ($this->services['prestashop.core.form.choice_provider.theme_by_name'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_ThemeByNameService.php'))->getChoices());
