<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.common.category_choice_tree' shared service.

return $this->services['form.type.common.category_choice_tree'] = new \PrestaShopBundle\Form\Admin\Type\CategoryChoiceTreeType(($this->services['prestashop.adapter.form.choice_provider.category_tree_choice_provider'] ?? $this->load('getPrestashop_Adapter_Form_ChoiceProvider_CategoryTreeChoiceProviderService.php'))->getChoices());
