<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.localization_configuration' shared service.

return $this->services['form.type.localization_configuration'] = new \PrestaShopBundle\Form\Admin\Improve\International\Localization\LocalizationConfigurationType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getLanguages(), ($this->services['prestashop.core.form.choice_provider.language_by_id'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_LanguageByIdService.php'))->getChoices(), ($this->services['prestashop.core.form.choice_provider.country_by_id'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_CountryByIdService.php'))->getChoices(), ($this->services['prestashop.core.form.choice_provider.currency_by_id'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_CurrencyByIdService.php'))->getChoices(), ($this->services['prestashop.core.form.choice_provider.timezone_by_name'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_TimezoneByNameService.php'))->getChoices());
