<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\PrestaShop\Core\Domain\Product\Combination\QueryHandler\GetCombinationIdsHandler' shared autowired service.

return $this->services['PrestaShop\\PrestaShop\\Core\\Domain\\Product\\Combination\\QueryHandler\\GetCombinationIdsHandler'] = new \PrestaShop\PrestaShop\Core\Domain\Product\Combination\QueryHandler\GetCombinationIdsHandler(($this->services['PrestaShop\\PrestaShop\\Core\\Grid\\Query\\ProductCombinationQueryBuilder'] ?? $this->load('getProductCombinationQueryBuilderService.php')));
