<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\PrestaShop\Adapter\Feature\QueryHandler\GetFeatureForEditingHandler' shared service.

return $this->services['PrestaShop\\PrestaShop\\Adapter\\Feature\\QueryHandler\\GetFeatureForEditingHandler'] = new \PrestaShop\PrestaShop\Adapter\Feature\QueryHandler\GetFeatureForEditingHandler();
