<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Api\StateProvider\HookStatusProvider' shared autowired service.

return $this->privates['PrestaShopBundle\\Api\\StateProvider\\HookStatusProvider'] = new \PrestaShopBundle\Api\StateProvider\HookStatusProvider(($this->services['prestashop.core.query_bus'] ?? $this->load('getPrestashop_Core_QueryBusService.php')));
