<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Util\Number\NumberExtractor' shared autowired service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Util\\Number\\NumberExtractor'] = new \PrestaShop\PrestaShop\Core\Util\Number\NumberExtractor(($this->privates['property_accessor'] ?? $this->getPropertyAccessorService()));
