<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShopBundle\Form\Extension\NumberTypeExtension' shared autowired service.

return $this->privates['PrestaShopBundle\\Form\\Extension\\NumberTypeExtension'] = new \PrestaShopBundle\Form\Extension\NumberTypeExtension(($this->privates['PrestaShop\\PrestaShop\\Core\\Localization\\Number\\LocaleNumberTransformer'] ?? $this->load('getLocaleNumberTransformerService.php')));
