<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.form.choice_provider.order_state_by_id' shared service.

return $this->services['prestashop.core.form.choice_provider.order_state_by_id'] = new \PrestaShop\PrestaShop\Core\Form\ChoiceProvider\OrderStateByIdChoiceProvider(($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getLanguage()->id, ($this->services['prestashop.adapter.data_provider.order_state'] ?? ($this->services['prestashop.adapter.data_provider.order_state'] = new \PrestaShop\PrestaShop\Adapter\OrderState\OrderStateDataProvider())), ($this->services['PrestaShop\\PrestaShop\\Core\\Util\\ColorBrightnessCalculator'] ?? ($this->services['PrestaShop\\PrestaShop\\Core\\Util\\ColorBrightnessCalculator'] = new \PrestaShop\PrestaShop\Core\Util\ColorBrightnessCalculator())), ($this->services['translator'] ?? $this->getTranslatorService()));
