<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.manufacturer.query_handler.get_manufacturer_for_editing' shared service.

return $this->services['prestashop.adapter.manufacturer.query_handler.get_manufacturer_for_editing'] = new \PrestaShop\PrestaShop\Adapter\Manufacturer\QueryHandler\GetManufacturerForEditingHandler(($this->services['prestashop.core.image.parser.image_tag_source_parser'] ?? ($this->services['prestashop.core.image.parser.image_tag_source_parser'] = new \PrestaShop\PrestaShop\Core\Image\Parser\ImageTagSourceParser())));
