<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.form.identifiable_object.option_provider.customer_address_form_options_provider' shared service.

return $this->services['prestashop.core.form.identifiable_object.option_provider.customer_address_form_options_provider'] = new \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\OptionProvider\CustomerAddressFormOptionsProvider(($this->services['prestashop.core.query_bus'] ?? $this->load('getPrestashop_Core_QueryBusService.php')));
