<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.administration.upload_quota.form_provider' shared service.

return $this->services['prestashop.adapter.administration.upload_quota.form_provider'] = new \PrestaShopBundle\Form\Admin\Configure\AdvancedParameters\Administration\UploadQuotaDataProvider(($this->services['prestashop.adapter.upload_quota.configuration'] ?? $this->load('getPrestashop_Adapter_UploadQuota_ConfigurationService.php')));
