<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.data_provider.order_state' shared service.

return $this->services['prestashop.adapter.data_provider.order_state'] = new \PrestaShop\PrestaShop\Adapter\OrderState\OrderStateDataProvider();
