<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.module.sourcehandler.zip' shared autowired service.

return $this->services['prestashop.module.sourcehandler.zip'] = new \PrestaShop\PrestaShop\Core\Module\SourceHandler\ZipSourceHandler((\dirname(__DIR__, 4).'/app/../modules'), ($this->services['translator'] ?? $this->getTranslatorService()));
