<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.bundle.twig.extension.js_router_metadata_extension' shared service.

return $this->services['prestashop.bundle.twig.extension.js_router_metadata_extension'] = new \PrestaShopBundle\Twig\Extension\JsRouterMetadataExtension(($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($this->services['security.csrf.token_manager'] ?? $this->getSecurity_Csrf_TokenManagerService()), ($this->services['prestashop.user_provider'] ?? $this->load('getPrestashop_UserProviderService.php'))->getUsername());
