<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.supplier.command_handler.delete_supplier_logo_image_handler' shared service.

return $this->services['prestashop.adapter.supplier.command_handler.delete_supplier_logo_image_handler'] = new \PrestaShop\PrestaShop\Adapter\Supplier\CommandHandler\DeleteSupplierLogoImageHandler((\dirname(__DIR__, 4).'/img/su/'), (\dirname(__DIR__, 4).'/img/tmp/'));
