<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.store.command_handler.toggle_store_status' shared service.

return $this->services['prestashop.adapter.store.command_handler.toggle_store_status'] = new \PrestaShop\PrestaShop\Adapter\Store\CommandHandler\ToggleStoreStatusHandler(($this->services['prestashop.core.domain.store.repository.store_repository'] ?? ($this->services['prestashop.core.domain.store.repository.store_repository'] = new \PrestaShop\PrestaShop\Core\Domain\Store\Repository\StoreRepository())));
