<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.bundle.form.admin.sell.customer.transfer_guest_account' shared service.

return $this->services['prestashop.bundle.form.admin.sell.customer.transfer_guest_account'] = new \PrestaShopBundle\Form\Admin\Sell\Customer\TransferGuestAccountType(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getLanguages());
