<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.filter.credit_slip_form_factory' shared service.

return $this->services['prestashop.core.grid.filter.credit_slip_form_factory'] = new \PrestaShop\PrestaShop\Core\Grid\Filter\FilterFormFactoryFormActionDecorator(($this->services['prestashop.core.grid.filter.form_factory'] ?? $this->load('getPrestashop_Core_Grid_Filter_FormFactoryService.php')), ($this->services['prestashop.router'] ?? $this->load('getPrestashop_RouterService.php')), 'admin_credit_slips_search');
