<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.address.command_handler.edit_order_address_handler' shared service.

return $this->services['prestashop.adapter.address.command_handler.edit_order_address_handler'] = new \PrestaShop\PrestaShop\Adapter\Address\CommandHandler\EditOrderAddressHandler(($this->services['prestashop.adapter.address.command_handler.edit_customer_address_handler'] ?? ($this->services['prestashop.adapter.address.command_handler.edit_customer_address_handler'] = new \PrestaShop\PrestaShop\Adapter\Address\CommandHandler\EditCustomerAddressHandler())), ($this->services['prestashop.adapter.order.command_handler.change_order_delivery_address_handler'] ?? $this->load('getPrestashop_Adapter_Order_CommandHandler_ChangeOrderDeliveryAddressHandlerService.php')), ($this->services['prestashop.adapter.order.command_handler.change_order_invoice_address_handler'] ?? $this->load('getPrestashop_Adapter_Order_CommandHandler_ChangeOrderInvoiceAddressHandlerService.php')));
