<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.translation.translations_factory' shared service.

$this->services['prestashop.translation.translations_factory'] = $instance = new \PrestaShopBundle\Translation\Factory\TranslationsFactory();

$instance->addProvider(($this->services['prestashop.translation.backoffice_provider'] ?? $this->load('getPrestashop_Translation_BackofficeProviderService.php')));
$instance->addProvider(($this->services['prestashop.translation.frontoffice_provider'] ?? $this->load('getPrestashop_Translation_FrontofficeProviderService.php')));
$instance->addProvider(($this->services['prestashop.translation.mails_provider'] ?? $this->load('getPrestashop_Translation_MailsProviderService.php')));
$instance->addProvider(($this->services['prestashop.translation.mails_body_provider'] ?? $this->load('getPrestashop_Translation_MailsBodyProviderService.php')));
$instance->addProvider(($this->services['prestashop.translation.others_provider'] ?? $this->load('getPrestashop_Translation_OthersProviderService.php')));
$instance->addProvider(($this->services['prestashop.translation.modules_provider'] ?? $this->load('getPrestashop_Translation_ModulesProviderService.php')));
$instance->addProvider(($this->services['prestashop.translation.external_module_provider'] ?? $this->load('getPrestashop_Translation_ExternalModuleProviderService.php')));
$instance->addProvider(($this->services['prestashop.translation.module_provider'] ?? $this->load('getPrestashop_Translation_ModuleProviderService.php')));
$instance->addProvider(($this->services['prestashop.translation.search_provider'] ?? $this->load('getPrestashop_Translation_SearchProviderService.php')));

return $instance;
