<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.kpi_row.factory.customers' shared service.

return $this->services['prestashop.core.kpi_row.factory.customers'] = new \PrestaShop\PrestaShop\Core\Kpi\Row\HookableKpiRowFactory([0 => ($this->services['prestashop.adapter.kpi.most_common_customers_gender'] ?? $this->load('getPrestashop_Adapter_Kpi_MostCommonCustomersGenderService.php')), 1 => ($this->services['prestashop.adapter.kpi.average_customer_age'] ?? $this->load('getPrestashop_Adapter_Kpi_AverageCustomerAgeService.php')), 2 => ($this->services['prestashop.adapter.kpi.order_per_customer'] ?? $this->load('getPrestashop_Adapter_Kpi_OrderPerCustomerService.php')), 3 => ($this->services['prestashop.adapter.kpi.newsletter_registrations'] ?? $this->load('getPrestashop_Adapter_Kpi_NewsletterRegistrationsService.php'))], ($this->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? $this->getHookDispatcherService()), 'customers');
