<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.mail_template.partial_template_renderer' shared service.

return $this->services['prestashop.adapter.mail_template.partial_template_renderer'] = new \PrestaShop\PrestaShop\Adapter\MailTemplate\MailPartialTemplateRenderer(($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getSmarty());
