<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.kpi.abandoned_cart' shared service.

return $this->services['prestashop.adapter.kpi.abandoned_cart'] = new \PrestaShop\PrestaShop\Adapter\Kpi\AbandonedCartKpi();
