<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.twig.extension.stringloader' shared service.

return $this->services['prestashop.twig.extension.stringloader'] = new \Twig\Extension\StringLoaderExtension();
