<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\PrestaShop\Adapter\Product\Update\Filler\ProductFiller' shared service.

return $this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Update\\Filler\\ProductFiller'] = new \PrestaShop\PrestaShop\Adapter\Product\Update\Filler\ProductFiller(new RewindableGenerator(function () {
    yield 0 => ($this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Update\\Filler\\BasicInformationFiller'] ?? $this->load('getBasicInformationFillerService.php'));
    yield 1 => ($this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Update\\Filler\\OptionsFiller'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Update\\Filler\\OptionsFiller'] = new \PrestaShop\PrestaShop\Adapter\Product\Update\Filler\OptionsFiller()));
    yield 2 => ($this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Update\\Filler\\PricesFiller'] ?? $this->load('getPricesFiller2Service.php'));
    yield 3 => ($this->privates['PrestaShop\\PrestaShop\\Adapter\\Product\\Update\\Filler\\SeoFiller'] ?? $this->load('getSeoFillerService.php'));
    yield 4 => ($this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Update\\Filler\\DetailsFiller'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Update\\Filler\\DetailsFiller'] = new \PrestaShop\PrestaShop\Adapter\Product\Update\Filler\DetailsFiller()));
    yield 5 => ($this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Update\\Filler\\ShippingFiller'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Update\\Filler\\ShippingFiller'] = new \PrestaShop\PrestaShop\Adapter\Product\Update\Filler\ShippingFiller()));
    yield 6 => ($this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Update\\Filler\\StockInformationFiller'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Update\\Filler\\StockInformationFiller'] = new \PrestaShop\PrestaShop\Adapter\Product\Update\Filler\StockInformationFiller()));
}, 7));
