<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.order_return_state.repository.order_return_state_repository' shared service.

return $this->services['prestashop.adapter.order_return_state.repository.order_return_state_repository'] = new \PrestaShop\PrestaShop\Adapter\OrderReturnState\Repository\OrderReturnStateRepository();
