<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.order.command_handler.duplicate_order_cart_handler' shared service.

return $this->services['prestashop.adapter.order.command_handler.duplicate_order_cart_handler'] = new \PrestaShop\PrestaShop\Adapter\Order\CommandHandler\DuplicateOrderCartHandler(($this->services['PrestaShop\\PrestaShop\\Adapter\\ContextStateManager'] ?? $this->load('getContextStateManagerService.php')));
