<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.KyDuqrl.PrestaShop\PrestaShop\Core\Search\Filters\ProductCombinationFilters' shared service.

$this->throw('Cannot autowire service ".service_locator.KyDuqrl": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ProductCombinationFilters" but no such service exists.');
