<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.admin.email_configuration.form_data_provider' shared service.

return $this->services['prestashop.admin.email_configuration.form_data_provider'] = new \PrestaShopBundle\Form\Admin\Configure\AdvancedParameters\Email\EmailConfigurationFormDataProvider(($this->services['prestashop.core.email.email_configurator'] ?? $this->load('getPrestashop_Core_Email_EmailConfiguratorService.php')));
