<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.import.handler_finder' shared service.

return $this->services['prestashop.adapter.import.handler_finder'] = new \PrestaShop\PrestaShop\Adapter\Import\Handler\ImportHandlerFinder(($this->services['prestashop.adapter.import.handler.category'] ?? $this->load('getPrestashop_Adapter_Import_Handler_CategoryService.php')), ($this->services['prestashop.adapter.import.handler.product'] ?? $this->load('getPrestashop_Adapter_Import_Handler_ProductService.php')));
