<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.system_information' shared service.

return $this->services['prestashop.adapter.system_information'] = new \PrestaShop\PrestaShop\Adapter\System\SystemInformation(($this->services['prestashop.adapter.hosting_information'] ?? ($this->services['prestashop.adapter.hosting_information'] = new \PrestaShop\PrestaShop\Adapter\Hosting\HostingInformation())), ($this->services['prestashop.adapter.mailing_information'] ?? ($this->services['prestashop.adapter.mailing_information'] = new \PrestaShop\PrestaShop\Adapter\Mail\MailingInformation())), ($this->services['prestashop.adapter.shop_information'] ?? $this->load('getPrestashop_Adapter_ShopInformationService.php')));
