<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.security.command_handler.bulk_delete_customers_sessions_handler' shared service.

return $this->services['prestashop.adapter.security.command_handler.bulk_delete_customers_sessions_handler'] = new \PrestaShop\PrestaShop\Adapter\Security\CommandHandler\BulkDeleteCustomerSessionsHandler(($this->services['prestashop.adapter.security.repository.customer_session_repository'] ?? $this->load('getPrestashop_Adapter_Security_Repository_CustomerSessionRepositoryService.php')));
