<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.translation.external_module_provider' shared service.

return $this->services['prestashop.translation.external_module_provider'] = new \PrestaShopBundle\Translation\Provider\ExternalModuleLegacySystemProvider(($this->services['prestashop.translation.database_loader'] ?? $this->load('getPrestashop_Translation_DatabaseLoaderService.php')), (\dirname(__DIR__, 4).'/app/../modules'), ($this->services['prestashop.translation.legacy_file_loader'] ?? $this->load('getPrestashop_Translation_LegacyFileLoaderService.php')), ($this->services['prestashop.translation.legacy_module.extractor'] ?? $this->load('getPrestashop_Translation_LegacyModule_ExtractorService.php')), ($this->services['prestashop.translation.module_provider'] ?? $this->load('getPrestashop_Translation_ModuleProviderService.php')));
