<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.order.refund.order_refund_calculator' shared service.

return $this->services['prestashop.adapter.order.refund.order_refund_calculator'] = new \PrestaShop\PrestaShop\Adapter\Order\Refund\OrderRefundCalculator();
