<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.translation.api.stock' shared service.

$this->services['prestashop.translation.api.stock'] = $instance = new \PrestaShopBundle\Translation\Api\StockApi();

$instance->setTranslator(($this->services['translator'] ?? $this->getTranslatorService()));

return $instance;
