<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.order_return.command_handler.update_order_return_state_handler' shared service.

return $this->services['prestashop.adapter.order_return.command_handler.update_order_return_state_handler'] = new \PrestaShop\PrestaShop\Adapter\OrderReturn\CommandHandler\UpdateOrderReturnStateHandler(($this->services['prestashop.adapter.order_return.repository.order_return_repository'] ?? $this->load('getPrestashop_Adapter_OrderReturn_Repository_OrderReturnRepositoryService.php')), ($this->services['prestashop.adapter.order_return_state.repository.order_return_state_repository'] ?? ($this->services['prestashop.adapter.order_return_state.repository.order_return_state_repository'] = new \PrestaShop\PrestaShop\Adapter\OrderReturnState\Repository\OrderReturnStateRepository())));
