<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.order.query_handler.get_order_for_viewing_handler' shared service.

return $this->services['prestashop.adapter.order.query_handler.get_order_for_viewing_handler'] = new \PrestaShop\PrestaShop\Adapter\Order\QueryHandler\GetOrderForViewingHandler(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getContext()->language->id, ($this->services['prestashop.core.localization.locale.context_locale'] ?? $this->load('getPrestashop_Core_Localization_Locale_ContextLocaleService.php')), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getContext(), ($this->services['prestashop.adapter.data_provider.customer'] ?? ($this->services['prestashop.adapter.data_provider.customer'] = new \PrestaShop\PrestaShop\Adapter\Customer\CustomerDataProvider())), ($this->services['prestashop.adapter.order.query_handler.get_order_products_for_viewing_handler'] ?? $this->load('getPrestashop_Adapter_Order_QueryHandler_GetOrderProductsForViewingHandlerService.php')), ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())), ($this->services['prestashop.adapter.address.formatter'] ?? ($this->services['prestashop.adapter.address.formatter'] = new \PrestaShop\PrestaShop\Adapter\Address\AddressFormatter())));
