<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.bundle.twig.extension.column' shared service.

$a = ($this->services['twig'] ?? $this->load('getTwigService.php'));

if (isset($this->services['prestashop.bundle.twig.extension.column'])) {
    return $this->services['prestashop.bundle.twig.extension.column'];
}

return $this->services['prestashop.bundle.twig.extension.column'] = new \PrestaShopBundle\Twig\Extension\GridExtension($a, ($this->services['prestashop.static_cache.adapter'] ?? $this->getPrestashop_StaticCache_AdapterService()));
