<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.translation.theme_provider' shared service.

$this->services['prestashop.translation.theme_provider'] = $instance = new \PrestaShopBundle\Translation\Provider\ThemeProvider(($this->services['prestashop.translation.database_loader'] ?? $this->load('getPrestashop_Translation_DatabaseLoaderService.php')), ($this->targetDir.''.'/themes'));

$instance->themeResourcesDirectory = (\dirname(__DIR__, 4).'/app/../themes');
$instance->filesystem = ($this->services['filesystem'] ?? ($this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem()));
$instance->themeRepository = ($this->services['prestashop.core.addon.theme.repository'] ?? $this->load('getPrestashop_Core_Addon_Theme_RepositoryService.php'));
$instance->themeExtractor = ($this->services['prestashop.translation.theme_extractor'] ?? $this->load('getPrestashop_Translation_ThemeExtractorService.php'));
$instance->defaultTranslationDir = (\dirname(__DIR__, 4).'/app/../translations');

return $instance;
