<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.security.general.form_provider' shared service.

return $this->services['prestashop.adapter.security.general.form_provider'] = new \PrestaShopBundle\Form\Admin\Configure\AdvancedParameters\Security\FormDataProvider(($this->services['prestashop.adapter.security.general.configuration'] ?? $this->load('getPrestashop_Adapter_Security_General_ConfigurationService.php')));
