<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.routes.route_validator' shared service.

return $this->services['prestashop.adapter.routes.route_validator'] = new \PrestaShop\PrestaShop\Adapter\Routes\RouteValidator();
