<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.file.cached_finder.invoice_model' shared service.

return $this->services['prestashop.core.file.cached_finder.invoice_model'] = new \PrestaShop\PrestaShop\Core\Proxy\CachedFileFinderProxy(($this->services['prestashop.core.file.finder.invoice_model'] ?? $this->load('getPrestashop_Core_File_Finder_InvoiceModelService.php')));
