<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.command_handler.add_product_to_cart_handler' shared service.

return $this->services['prestashop.adapter.command_handler.add_product_to_cart_handler'] = new \PrestaShop\PrestaShop\Adapter\Cart\CommandHandler\AddProductToCartHandler(($this->services['prestashop.adapter.command_handler.add_customization_handler'] ?? ($this->services['prestashop.adapter.command_handler.add_customization_handler'] = new \PrestaShop\PrestaShop\Adapter\Cart\CommandHandler\AddCustomizationHandler())), ($this->services['prestashop.adapter.command_handler.update_product_quantity_in_cart_handler'] ?? $this->load('getPrestashop_Adapter_CommandHandler_UpdateProductQuantityInCartHandlerService.php')));
