<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.attachment.uploader.attachment_file_uploader' shared service.

return $this->services['prestashop.adapter.attachment.uploader.attachment_file_uploader'] = new \PrestaShop\PrestaShop\Adapter\File\Uploader\AttachmentFileUploader(($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())), ($this->services['prestashop.core.configuration.upload_size_configuration'] ?? $this->load('getPrestashop_Core_Configuration_UploadSizeConfigurationService.php')));
