<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.bridge.smarty.smarty_bridge' shared service.

return $this->services['prestashop.bridge.smarty.smarty_bridge'] = new \PrestaShopBundle\Bridge\Smarty\SmartyBridge(($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())), new RewindableGenerator(function () {
    yield 0 => ($this->services['prestashop.bridge.smarty.breadcrumbs_and_title_configurator'] ?? $this->load('getPrestashop_Bridge_Smarty_BreadcrumbsAndTitleConfiguratorService.php'));
    yield 1 => ($this->services['prestashop.bridge.smarty.footer_configurator'] ?? $this->load('getPrestashop_Bridge_Smarty_FooterConfiguratorService.php'));
    yield 2 => ($this->services['prestashop.bridge.smarty.header_configurator'] ?? $this->load('getPrestashop_Bridge_Smarty_HeaderConfiguratorService.php'));
    yield 3 => ($this->services['prestashop.bridge.smarty.modal_configurator'] ?? ($this->services['prestashop.bridge.smarty.modal_configurator'] = new \PrestaShopBundle\Bridge\Smarty\ModalConfigurator()));
    yield 4 => ($this->services['prestashop.bridge.smarty.notification_configurator'] ?? $this->load('getPrestashop_Bridge_Smarty_NotificationConfiguratorService.php'));
    yield 5 => ($this->services['prestashop.bridge.smarty.toolbar_flags_configurator'] ?? $this->load('getPrestashop_Bridge_Smarty_ToolbarFlagsConfiguratorService.php'));
}, 6));
