<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.domain.theme.command_handler.import_theme_handler' shared service.

return $this->services['prestashop.core.domain.theme.command_handler.import_theme_handler'] = new \PrestaShop\PrestaShop\Core\Domain\Theme\CommandHandler\ImportThemeHandler(($this->services['prestashop.core.addon.theme.theme_zip_uploader'] ?? $this->load('getPrestashop_Core_Addon_Theme_ThemeZipUploaderService.php')), ($this->services['prestashop.core.addon.theme.theme_manager'] ?? $this->load('getPrestashop_Core_Addon_Theme_ThemeManagerService.php')), ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())));
