<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\PrestaShop\Adapter\Product\Image\ProductImagePathFactory' shared service.

return $this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Image\\ProductImagePathFactory'] = new \PrestaShop\PrestaShop\Adapter\Product\Image\ProductImagePathFactory(($this->services['prestashop.adapter.shop.url.product_image_folder_provider'] ?? $this->load('getPrestashop_Adapter_Shop_Url_ProductImageFolderProviderService.php'))->getUrl(), (\dirname(__DIR__, 4).'/img/tmp/'), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getContext()->language->iso_code);
