<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.form.choice_provider.module_by_name' shared service.

return $this->services['prestashop.core.form.choice_provider.module_by_name'] = new \PrestaShop\PrestaShop\Core\Form\ChoiceProvider\ModuleByNameChoiceProvider(($this->services['prestashop.core.admin.module.repository'] ?? $this->getPrestashop_Core_Admin_Module_RepositoryService())->getInstalledModules());
