<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.order.command_handler.send_process_order_email_handler' shared service.

return $this->services['prestashop.adapter.order.command_handler.send_process_order_email_handler'] = new \PrestaShop\PrestaShop\Adapter\Order\CommandHandler\SendProcessOrderEmailHandler(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getContext()->link);
