<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.admin.order.invoices.by_date.form_handler' shared service.

return $this->services['prestashop.admin.order.invoices.by_date.form_handler'] = new \PrestaShopBundle\Form\Admin\Sell\Order\Invoices\InvoiceByDateFormHandler(($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php')), ($this->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? $this->getHookDispatcherService()), ($this->services['prestashop.admin.order.invoices.by_date.data_provider'] ?? $this->load('getPrestashop_Admin_Order_Invoices_ByDate_DataProviderService.php')), 'PrestaShopBundle\\Form\\Admin\\Sell\\Order\\Invoices\\GenerateByDateType', 'OrdersInvoicesByDate', ($this->services['prestashop.adapter.data_provider.order_invoice'] ?? ($this->services['prestashop.adapter.data_provider.order_invoice'] = new \PrestaShop\PrestaShop\Adapter\Invoice\OrderInvoiceDataProvider())), ($this->services['prestashop.adapter.pdf.generator.invoice'] ?? $this->load('getPrestashop_Adapter_Pdf_Generator_InvoiceService.php')));
