<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.definition.factory.monitoring.empty_category' shared service.

$this->services['prestashop.core.grid.definition.factory.monitoring.empty_category'] = $instance = new \PrestaShop\PrestaShop\Core\Grid\Definition\Factory\Monitoring\EmptyCategoryGridDefinitionFactory(($this->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? $this->getHookDispatcherService()), ($this->services['prestashop.adapter.grid.action.row.accessibility_checker.category_for_view'] ?? $this->load('getPrestashop_Adapter_Grid_Action_Row_AccessibilityChecker_CategoryForViewService.php')));

$instance->setTranslator(($this->services['translator'] ?? $this->getTranslatorService()));

return $instance;
