<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.module.tab.register' shared service.

return $this->services['prestashop.adapter.module.tab.register'] = new \PrestaShop\PrestaShop\Adapter\Module\Tab\ModuleTabRegister(($this->services['prestashop.core.admin.tab.repository'] ?? $this->load('getPrestashop_Core_Admin_Tab_RepositoryService.php')), ($this->services['prestashop.core.admin.lang.repository'] ?? $this->getPrestashop_Core_Admin_Lang_RepositoryService()), ($this->services['logger'] ?? $this->getLoggerService()), ($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['filesystem'] ?? ($this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem())), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getLanguages(), ($this->privates['routing.loader.yml'] ?? $this->load('getRouting_Loader_YmlService.php')));
