<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.data.factory.outstanding_decorator' shared service.

return $this->services['prestashop.core.grid.data.factory.outstanding_decorator'] = new \PrestaShop\PrestaShop\Core\Grid\Data\Factory\OutstandingGridDataFactory(($this->services['prestashop.core.grid.data.factory.outstanding'] ?? $this->load('getPrestashop_Core_Grid_Data_Factory_OutstandingService.php')), ($this->services['PrestaShop\\PrestaShop\\Core\\Localization\\Locale\\Repository'] ?? $this->getRepositoryService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getContext()->language->getLocale());
