<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.admin.shipping_preferences.handling.data_provider' shared service.

return $this->services['prestashop.admin.shipping_preferences.handling.data_provider'] = new \PrestaShopBundle\Form\Admin\Improve\Shipping\Preferences\PreferencesHandlingFormDataProvider(($this->services['prestashop.adapter.shipping_preferences.handling_configuration'] ?? $this->load('getPrestashop_Adapter_ShippingPreferences_HandlingConfigurationService.php')));
