<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.admin.order_preferences.gift_options.data_provider' shared service.

return $this->services['prestashop.admin.order_preferences.gift_options.data_provider'] = new \PrestaShopBundle\Form\Admin\Configure\ShopParameters\OrderPreferences\OrderPreferencesGiftOptionsFormDataProvider(($this->services['prestashop.adapter.order_gift.configuration'] ?? $this->load('getPrestashop_Adapter_OrderGift_ConfigurationService.php')), ($this->services['translator'] ?? $this->getTranslatorService()));
