<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.catalog_price_rule.query_handler.get_catalog_price_rule_list_for_product_handler' shared service.

return $this->services['prestashop.adapter.catalog_price_rule.query_handler.get_catalog_price_rule_list_for_product_handler'] = new \PrestaShop\PrestaShop\Adapter\CatalogPriceRule\QueryHandler\GetCatalogPriceRuleListForProductHandler(($this->services['prestashop.adapter.catalog_price_rule.repository.catalog_price_rule_repository'] ?? $this->load('getPrestashop_Adapter_CatalogPriceRule_Repository_CatalogPriceRuleRepositoryService.php')));
