<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.order.delivery.slip.pdf.form_handler' shared service.

return $this->services['prestashop.adapter.order.delivery.slip.pdf.form_handler'] = new \PrestaShop\PrestaShop\Core\Form\Handler(($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php')), ($this->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? $this->getHookDispatcherService()), ($this->services['prestashop.adapter.order.delivery.slip.pdf.form_provider'] ?? $this->load('getPrestashop_Adapter_Order_Delivery_Slip_Pdf_FormProviderService.php')), 'PrestaShopBundle\\Form\\Admin\\Sell\\Order\\Delivery\\SlipPdfType', 'OrderDeliverySlipPdf', 'slip_pdf_form');
