<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.form.choice_provider.pack_stock_type_choice_provider' shared service.

return $this->services['prestashop.core.form.choice_provider.pack_stock_type_choice_provider'] = new \PrestaShop\PrestaShop\Core\Form\ChoiceProvider\PackStockTypeChoiceProvider(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration()))->getInt("PS_PACK_STOCK_TYPE"));
