<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.preferences.form_provider' shared service.

return $this->services['prestashop.adapter.preferences.form_provider'] = new \PrestaShopBundle\Form\Admin\Configure\ShopParameters\General\PreferencesFormDataProvider(($this->services['prestashop.adapter.preferences.configuration'] ?? $this->load('getPrestashop_Adapter_Preferences_ConfigurationService.php')));
