<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.currency.query_handler.get_reference_currency' shared service.

return $this->services['prestashop.adapter.currency.query_handler.get_reference_currency'] = new \PrestaShop\PrestaShop\Adapter\Currency\QueryHandler\GetReferenceCurrencyHandler(($this->services['prestashop.core.localization.cldr.locale_repository'] ?? $this->getPrestashop_Core_Localization_Cldr_LocaleRepositoryService()), ($this->services['prestashop.core.admin.lang.repository'] ?? $this->getPrestashop_Core_Admin_Lang_RepositoryService())->findAll());
