<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.bridge.smarty.toolbar_flags_configurator' shared service.

return $this->services['prestashop.bridge.smarty.toolbar_flags_configurator'] = new \PrestaShopBundle\Bridge\Smarty\ToolbarFlagsConfigurator(($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())), ($this->services['PrestaShop\\PrestaShop\\Core\\Help\\Documentation'] ?? $this->load('getDocumentationService.php')), ($this->services['prestashop.adapter.environment'] ?? ($this->services['prestashop.adapter.environment'] = new \PrestaShop\PrestaShop\Adapter\Environment(false)))->isDebug());
