<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.factory.title_decorator' shared service.

return $this->services['prestashop.core.grid.factory.title_decorator'] = new \PrestaShop\PrestaShop\Core\Grid\Data\Factory\TitleGridDataFactory(($this->services['prestashop.core.grid.data.factory.title'] ?? $this->load('getPrestashop_Core_Grid_Data_Factory_TitleService.php')), ($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['prestashop.adapter.title.title_image_thumbnail_provider'] ?? $this->load('getPrestashop_Adapter_Title_TitleImageThumbnailProviderService.php')));
