<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.admin.module.repository.eventsubscriber' shared service.

return $this->services['prestashop.core.admin.module.repository.eventsubscriber'] = new \PrestaShop\PrestaShop\Core\Module\EventSubscriber(($this->services['prestashop.core.admin.module.repository'] ?? $this->getPrestashop_Core_Admin_Module_RepositoryService()), ($this->services['prestashop.adapter.cache.clearer.symfony_cache_clearer'] ?? ($this->services['prestashop.adapter.cache.clearer.symfony_cache_clearer'] = new \PrestaShop\PrestaShop\Adapter\Cache\Clearer\SymfonyCacheClearer())));
