<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.module.link_block.grid.factory' shared service.

return $this->services['prestashop.module.link_block.grid.factory'] = new \PrestaShop\Module\LinkList\Core\Grid\LinkBlockGridFactory(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['prestashop.module.link_block.grid.data_factory'] ?? $this->load('getPrestashop_Module_LinkBlock_Grid_DataFactoryService.php')), ($this->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? $this->getHookDispatcherService()), ($this->services['prestashop.core.grid.filter.form_factory'] ?? $this->load('getPrestashop_Core_Grid_Filter_FormFactoryService.php')), ($this->services['prestashop.adapter.shop.context'] ?? ($this->services['prestashop.adapter.shop.context'] = new \PrestaShop\PrestaShop\Adapter\Shop\Context())));
