<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.image.uploader.employee_image_uploader' shared service.

return $this->services['prestashop.adapter.image.uploader.employee_image_uploader'] = new \PrestaShop\PrestaShop\Adapter\Image\Uploader\EmployeeImageUploader((\dirname(__DIR__, 4).'/img/e/'), (\dirname(__DIR__, 4).'/img/tmp/'));
