<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.translation.legacy_file_loader' shared service.

return $this->services['prestashop.translation.legacy_file_loader'] = new \PrestaShopBundle\Translation\Loader\LegacyFileLoader(($this->services['prestashop.translation.legacy_file_reader'] ?? $this->load('getPrestashop_Translation_LegacyFileReaderService.php')));
