<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.translation.loader.database' shared service.

return $this->services['prestashop.translation.loader.database'] = new \PrestaShop\PrestaShop\Core\Translation\Storage\Loader\DatabaseTranslationLoader(($this->services['prestashop.core.admin.lang.repository'] ?? $this->getPrestashop_Core_Admin_Lang_RepositoryService()), ($this->services['prestashop.core.admin.translation.repository'] ?? $this->load('getPrestashop_Core_Admin_Translation_RepositoryService.php')));
