<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.form.choice_provider.theme_by_name' shared service.

return $this->services['prestashop.core.form.choice_provider.theme_by_name'] = new \PrestaShop\PrestaShop\Core\Form\ChoiceProvider\ThemeByNameChoiceProvider(($this->services['prestashop.core.addon.theme.repository'] ?? $this->load('getPrestashop_Core_Addon_Theme_RepositoryService.php'))->getListAsCollection());
