<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.webservice.server_requirements_checker' shared service.

return $this->services['prestashop.core.webservice.server_requirements_checker'] = new \PrestaShop\PrestaShop\Core\Webservice\ServerRequirementsChecker(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())), ($this->services['prestashop.adapter.hosting_information'] ?? ($this->services['prestashop.adapter.hosting_information'] = new \PrestaShop\PrestaShop\Adapter\Hosting\HostingInformation())), ($this->services['prestashop.core.configuration.php_extension_checker'] ?? ($this->services['prestashop.core.configuration.php_extension_checker'] = new \PrestaShop\PrestaShop\Core\Configuration\PhpExtensionChecker())));
