<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.definition.factory.customer_thread' shared service.

$this->services['prestashop.core.grid.definition.factory.customer_thread'] = $instance = new \PrestaShop\PrestaShop\Core\Grid\Definition\Factory\CustomerThreadGridDefinitionFactory(($this->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? $this->getHookDispatcherService()), ($this->services['prestashop.core.form.choice_provider.contact_type_choice_provider'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_ContactTypeChoiceProviderService.php')), ($this->services['prestashop.adapter.form.choice_provider.shop_name_by_id'] ?? ($this->services['prestashop.adapter.form.choice_provider.shop_name_by_id'] = new \PrestaShop\PrestaShop\Adapter\Form\ChoiceProvider\ShopNameByIdChoiceProvider())), ($this->services['prestashop.core.form.choice_provider.customer_thread_statuses_choice_provider'] ?? $this->load('getPrestashop_Core_Form_ChoiceProvider_CustomerThreadStatusesChoiceProviderService.php')));

$instance->setTranslator(($this->services['translator'] ?? $this->getTranslatorService()));

return $instance;
