<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.cart_rule.query_handler.search_cart_rules_handler' shared service.

return $this->services['prestashop.adapter.cart_rule.query_handler.search_cart_rules_handler'] = new \PrestaShop\PrestaShop\Adapter\CartRule\QueryHandler\SearchCartRulesHandler(($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getContext()->language->id);
