<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.profile.permission.query_handler.get_permissions_for_configuration_handler' shared service.

return $this->services['prestashop.adapter.profile.permission.query_handler.get_permissions_for_configuration_handler'] = new \PrestaShop\PrestaShop\Adapter\Profile\Permission\QueryHandler\GetPermissionsForConfigurationHandler(($this->services['security.authorization_checker'] ?? $this->getSecurity_AuthorizationCheckerService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getContext()->language->id, [0 => 'AdminLogin', 1 => 'AdminQuickAccesses', 2 => 'AdminTabs']);
