<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.order.query_handler.get_order_products_for_viewing_handler' shared service.

return $this->services['prestashop.adapter.order.query_handler.get_order_products_for_viewing_handler'] = new \PrestaShop\PrestaShop\Adapter\Order\QueryHandler\GetOrderProductsForViewingHandler(($this->services['prestashop.core.image.parser.image_tag_source_parser'] ?? ($this->services['prestashop.core.image.parser.image_tag_source_parser'] = new \PrestaShop\PrestaShop\Core\Image\Parser\ImageTagSourceParser())), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService())->getContext()->language->id, ($this->services['prestashop.core.localization.locale.context_locale'] ?? $this->load('getPrestashop_Core_Localization_Locale_ContextLocaleService.php')));
