<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.language.pack.importer' shared service.

return $this->services['prestashop.adapter.language.pack.importer'] = new \PrestaShop\PrestaShop\Adapter\Language\Pack\LanguagePackImporter(($this->services['prestashop.adapter.language.language_pack_installer'] ?? $this->load('getPrestashop_Adapter_Language_LanguagePackInstallerService.php')), ($this->services['prestashop.core.cache.clearer.cache_clearer_chain'] ?? $this->load('getPrestashop_Core_Cache_Clearer_CacheClearerChainService.php')));
