<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.backup.backup_provider' shared autowired service.

return $this->services['prestashop.adapter.backup.backup_provider'] = new \PrestaShop\PrestaShop\Adapter\Backup\BackupRepository();
