<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.employee.command_handler.add_employee_handler' shared service.

return $this->services['prestashop.adapter.employee.command_handler.add_employee_handler'] = new \PrestaShop\PrestaShop\Adapter\Profile\Employee\CommandHandler\AddEmployeeHandler(($this->services['prestashop.core.crypto.hashing'] ?? ($this->services['prestashop.core.crypto.hashing'] = new \PrestaShop\PrestaShop\Core\Crypto\Hashing())), ($this->services['prestashop.core.employee.profile_access_checker'] ?? $this->load('getPrestashop_Core_Employee_ProfileAccessCheckerService.php')), ($this->services['prestashop.adapter.data_provider.employee'] ?? $this->load('getPrestashop_Adapter_DataProvider_EmployeeService.php')));
