<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.localization.configuration' shared service.

return $this->services['prestashop.adapter.localization.configuration'] = new \PrestaShop\PrestaShop\Adapter\Localization\LocalizationConfiguration(($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())), ($this->services['prestashop.adapter.language.activator'] ?? ($this->services['prestashop.adapter.language.activator'] = new \PrestaShop\PrestaShop\Adapter\Language\LanguageActivator())), ($this->services['prestashop.adapter.manager.currency'] ?? ($this->services['prestashop.adapter.manager.currency'] = new \PrestaShop\PrestaShop\Adapter\Currency\CurrencyManager())));
