<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.state.command_handler.toggle_state_status_handler' shared service.

return $this->services['prestashop.adapter.state.command_handler.toggle_state_status_handler'] = new \PrestaShop\PrestaShop\Adapter\State\CommandHandler\ToggleStateStatusHandler();
