<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.factory.cms_page' shared service.

return $this->services['prestashop.core.grid.factory.cms_page'] = new \PrestaShop\PrestaShop\Core\Grid\GridFactory(($this->services['prestashop.core.grid.definition.factory.cms_page'] ?? $this->load('getPrestashop_Core_Grid_Definition_Factory_CmsPageService.php')), ($this->services['prestashop.core.grid.data_provider.cms_page'] ?? $this->load('getPrestashop_Core_Grid_DataProvider_CmsPageService.php')), ($this->services['prestashop.core.grid.filter.cms_page_form_factory'] ?? $this->load('getPrestashop_Core_Grid_Filter_CmsPageFormFactoryService.php')), ($this->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? $this->getHookDispatcherService()));
