<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.domain.showcase_card.query_handler.get_showcase_card_is_closed_handler' shared service.

return $this->services['prestashop.core.domain.showcase_card.query_handler.get_showcase_card_is_closed_handler'] = new \PrestaShop\PrestaShop\Core\Domain\ShowcaseCard\QueryHandler\GetShowcaseCardIsClosedHandler(($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())), ($this->services['prestashop.core.showcase_card.configuration_map'] ?? ($this->services['prestashop.core.showcase_card.configuration_map'] = new \PrestaShop\PrestaShop\Core\Domain\ShowcaseCard\ConfigurationMap())));
