<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.hook.provider.identifiable_object_hook_by_form_type_provider' shared service.

return $this->services['prestashop.core.hook.provider.identifiable_object_hook_by_form_type_provider'] = new \PrestaShop\PrestaShop\Core\Hook\Provider\IdentifiableObjectHookByFormTypeProvider(($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php')));
