<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.util.string.string_validator' shared autowired service.

return $this->services['prestashop.core.util.string.string_validator'] = new \PrestaShop\PrestaShop\Core\Util\String\StringValidator();
