<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.order.amount.updater' shared service.

return $this->services['prestashop.adapter.order.amount.updater'] = new \PrestaShop\PrestaShop\Adapter\Order\OrderAmountUpdater(($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())), ($this->services['PrestaShop\\PrestaShop\\Adapter\\ContextStateManager'] ?? $this->load('getContextStateManagerService.php')), ($this->services['prestashop.adapter.order.order_detail.updater'] ?? $this->load('getPrestashop_Adapter_Order_OrderDetail_UpdaterService.php')), ($this->services['prestashop.adapter.order.product.remover'] ?? ($this->services['prestashop.adapter.order.product.remover'] = new \PrestaShop\PrestaShop\Adapter\Order\Refund\OrderProductRemover())));
