<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.command_handler.remove_cart_rule_from_cart_handler' shared service.

return $this->services['prestashop.adapter.command_handler.remove_cart_rule_from_cart_handler'] = new \PrestaShop\PrestaShop\Adapter\Cart\CommandHandler\RemoveCartRuleFromCartHandler();
