<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.hook.command_handler.get_hook_status_handler' shared service.

return $this->services['prestashop.adapter.hook.command_handler.get_hook_status_handler'] = new \PrestaShop\PrestaShop\Adapter\Hook\QueryHandler\GetHookStatusHandler();
