<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.meta.shop_url.configuration' shared service.

return $this->services['prestashop.adapter.meta.shop_url.configuration'] = new \PrestaShop\PrestaShop\Adapter\Meta\ShopUrlDataConfiguration(($this->services['prestashop.adapter.shop.shop_url'] ?? $this->load('getPrestashop_Adapter_Shop_ShopUrlService.php'))->getMainShopUrl(), ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())), ($this->services['prestashop.adapter.file.htaccess_file_generator'] ?? $this->load('getPrestashop_Adapter_File_HtaccessFileGeneratorService.php')));
