<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.mail_template.generator' shared service.

return $this->services['prestashop.core.mail_template.generator'] = new \PrestaShop\PrestaShop\Core\MailTemplate\MailTemplateGenerator(($this->services['prestashop.adapter.mail_template.twig_renderer'] ?? $this->load('getPrestashop_Adapter_MailTemplate_TwigRendererService.php')), ($this->services['logger'] ?? $this->getLoggerService()));
