<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.query_bus' shared autowired service.

return $this->services['prestashop.core.query_bus'] = new \PrestaShop\PrestaShop\Core\CommandBus\TacticianCommandBusAdapter(($this->services['tactician.commandbus.default'] ?? $this->load('getTactician_Commandbus_DefaultService.php')));
