<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.translation.theme.exporter' shared service.

$this->services['prestashop.translation.theme.exporter'] = $instance = new \PrestaShopBundle\Translation\Exporter\ThemeExporter(($this->services['prestashop.translation.theme_extractor'] ?? $this->load('getPrestashop_Translation_ThemeExtractorService.php')), ($this->services['prestashop.translation.theme_provider'] ?? $this->load('getPrestashop_Translation_ThemeProviderService.php')), ($this->services['prestashop.core.addon.theme.repository'] ?? $this->load('getPrestashop_Core_Addon_Theme_RepositoryService.php')), ($this->services['prestashop.translation.dumper.xliff'] ?? ($this->services['prestashop.translation.dumper.xliff'] = new \PrestaShop\TranslationToolsBundle\Translation\Dumper\XliffFileDumper())), ($this->services['prestashop.utils.zip_manager'] ?? ($this->services['prestashop.utils.zip_manager'] = new \PrestaShopBundle\Utils\ZipManager())), ($this->services['filesystem'] ?? ($this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem())));

$instance->cacheDir = $this->targetDir.'';
$instance->setExportDir(($this->targetDir.''.'/export'));

return $instance;
