<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\PrestaShop\Adapter\Product\SpecificPrice\CommandHandler\RemoveSpecificPricePriorityForProductHandler' shared service.

return $this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\SpecificPrice\\CommandHandler\\RemoveSpecificPricePriorityForProductHandler'] = new \PrestaShop\PrestaShop\Adapter\Product\SpecificPrice\CommandHandler\RemoveSpecificPricePriorityForProductHandler(($this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\SpecificPrice\\Update\\SpecificPricePriorityUpdater'] ?? $this->load('getSpecificPricePriorityUpdaterService.php')));
