<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Adapter\Product\Customization\CommandHandler\RemoveAllCustomizationFieldsFromProductHandler' shared autowired service.

return $this->privates['PrestaShop\\PrestaShop\\Adapter\\Product\\Customization\\CommandHandler\\RemoveAllCustomizationFieldsFromProductHandler'] = new \PrestaShop\PrestaShop\Adapter\Product\Customization\CommandHandler\RemoveAllCustomizationFieldsFromProductHandler(($this->privates['PrestaShop\\PrestaShop\\Adapter\\Product\\Customization\\Update\\CustomizationFieldDeleter'] ?? $this->load('getCustomizationFieldDeleterService.php')), ($this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Repository\\ProductRepository'] ?? $this->load('getProductRepositoryService.php')), ($this->privates['PrestaShop\\PrestaShop\\Adapter\\Product\\Customization\\Update\\ProductCustomizationFieldUpdater'] ?? $this->load('getProductCustomizationFieldUpdaterService.php')));
