<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\PrestaShop\Core\Module\SourceHandler\SourceHandlerFactory' shared service.

return $this->services['PrestaShop\\PrestaShop\\Core\\Module\\SourceHandler\\SourceHandlerFactory'] = new \PrestaShop\PrestaShop\Core\Module\SourceHandler\SourceHandlerFactory(new RewindableGenerator(function () {
    yield 0 => ($this->services['prestashop.module.sourcehandler.zip'] ?? $this->load('getPrestashop_Module_Sourcehandler_ZipService.php'));
    yield 1 => ($this->privates['PrestaShop\\PrestaShop\\Core\\Module\\SourceHandler\\RemoteZipSourceHandler'] ?? $this->load('getRemoteZipSourceHandlerService.php'));
}, 2));
