<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\PrestaShop\Adapter\Product\Pack\CommandHandler\SetPackProductsHandler' shared service.

return $this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Pack\\CommandHandler\\SetPackProductsHandler'] = new \PrestaShop\PrestaShop\Adapter\Product\Pack\CommandHandler\SetPackProductsHandler(($this->privates['PrestaShop\\PrestaShop\\Adapter\\Product\\Pack\\Update\\ProductPackUpdater'] ?? $this->load('getProductPackUpdaterService.php')));
