<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\PrestaShop\Adapter\Product\Customization\CommandHandler\SetProductCustomizationFieldsHandler' shared service.

return $this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Customization\\CommandHandler\\SetProductCustomizationFieldsHandler'] = new \PrestaShop\PrestaShop\Adapter\Product\Customization\CommandHandler\SetProductCustomizationFieldsHandler(($this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Customization\\Repository\\CustomizationFieldRepository'] ?? $this->load('getCustomizationFieldRepositoryService.php')), ($this->privates['PrestaShop\\PrestaShop\\Adapter\\Product\\Customization\\Update\\ProductCustomizationFieldUpdater'] ?? $this->load('getProductCustomizationFieldUpdaterService.php')));
