<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\PrestaShop\Adapter\Product\CommandHandler\SetAssociatedProductCategoriesHandler' shared service.

return $this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\CommandHandler\\SetAssociatedProductCategoriesHandler'] = new \PrestaShop\PrestaShop\Adapter\Product\CommandHandler\SetAssociatedProductCategoriesHandler(($this->privates['PrestaShop\\PrestaShop\\Adapter\\Product\\Update\\ProductCategoryUpdater'] ?? $this->load('getProductCategoryUpdaterService.php')));
