<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sensio_framework_extra.routing.loader.annot_dir' shared service.

@trigger_error('The "sensio_framework_extra.routing.loader.annot_dir" service is deprecated since version 5.2', E_USER_DEPRECATED);

return new \Symfony\Component\Routing\Loader\AnnotationDirectoryLoader(($this->privates['file_locator'] ?? $this->load('getFileLocatorService.php')), ($this->privates['sensio_framework_extra.routing.loader.annot_class'] ?? $this->load('getSensioFrameworkExtra_Routing_Loader_AnnotClassService.php')));
