<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShopBundle\Command\ThemeEnablerCommand' shared service.

return $this->services['PrestaShopBundle\\Command\\ThemeEnablerCommand'] = new \PrestaShopBundle\Command\ThemeEnablerCommand(($this->services['prestashop.core.addon.theme.theme_manager'] ?? $this->load('getPrestashop_Core_Addon_Theme_ThemeManagerService.php')));
