<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\PrestaShop\Adapter\Product\Image\CommandHandler\UpdateProductImageHandler' shared service.

return $this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Image\\CommandHandler\\UpdateProductImageHandler'] = new \PrestaShop\PrestaShop\Adapter\Product\Image\CommandHandler\UpdateProductImageHandler(($this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Image\\Repository\\ProductImageRepository'] ?? $this->load('getProductImageRepositoryService.php')), ($this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Image\\Update\\ProductImageUpdater'] ?? $this->load('getProductImageUpdaterService.php')), ($this->privates['PrestaShop\\PrestaShop\\Adapter\\Product\\Image\\Uploader\\ProductImageUploader'] ?? $this->load('getProductImageUploaderService.php')), ($this->services['PrestaShop\\PrestaShop\\Adapter\\Image\\ProductImageFileValidator'] ?? $this->load('getProductImageFileValidatorService.php')));
