<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\PrestaShop\Adapter\Product\CommandHandler\UpdateProductsPositionsHandler' shared service.

return $this->services['PrestaShop\\PrestaShop\\Adapter\\Product\\CommandHandler\\UpdateProductsPositionsHandler'] = new \PrestaShop\PrestaShop\Adapter\Product\CommandHandler\UpdateProductsPositionsHandler(($this->services['prestashop.core.grid.product.position_definition'] ?? $this->load('getPrestashop_Core_Grid_Product_PositionDefinitionService.php')), ($this->services['PrestaShop\\PrestaShop\\Core\\Grid\\Position\\PositionUpdateFactory'] ?? $this->load('getPositionUpdateFactoryService.php')), ($this->services['PrestaShop\\PrestaShop\\Core\\Grid\\Position\\GridPositionUpdater'] ?? $this->load('getGridPositionUpdaterService.php')));
