<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\PrestaShop\Core\Util\Url\UrlFileCheckerInterface' shared autowired service.

return $this->services['PrestaShop\\PrestaShop\\Core\\Util\\Url\\UrlFileCheckerInterface'] = new \PrestaShop\PrestaShop\Core\Util\Url\UrlFileChecker(\dirname(__DIR__, 4));
