version: '3'

services:
  mysql:
    container_name: some-mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
    volumes:
      - dbdata:/var/lib/mysql

  prestashop:
    container_name: prestashop
<<<<<<< HEAD
    image: bannakorns/g04_prestashop:latest
=======
    image: prestashop/prestashop:latest
>>>>>>> 7d86c2e35d693e916888837f84410a519844f9fa
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      DB_SERVER: some-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
    networks:
      - prestashop_network
    volumes:
<<<<<<< HEAD
      - type: bind
        source: ./modules/testModule
        target: /var/www/html/modules/testModule
      - type: bind
        source: ./themes/myTheme
        target: /var/www/html/themes/myTheme
      - psdata:/var/www/html
=======
      - ./app/controllers:/var/www/html/controllers # To develop controller
      - ./app/modules:/var/www/html/modules # To develop module
      - ./app/themes/cp_theme:/var/www/html/themes/cp_theme # To develop theme
      - ./app/themes/child_cp_theme:/var/www/html/themes/child_cp_theme # To develop child theme
      - ./app/img:/var/www/html/img # To store image data
>>>>>>> 7d86c2e35d693e916888837f84410a519844f9fa

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    networks:
      - prestashop_network
    environment:
      PMA_HOST: some-mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - 8082:80

networks:
  prestashop_network:

volumes:
  psdata:
<<<<<<< HEAD
  dbdata:
=======
  dbdata:
>>>>>>> 7d86c2e35d693e916888837f84410a519844f9fa
