version: '3'

services:
  prestashop:
    image: bannakorns/g04_prestashop
    environment:
      - DB_SERVER=db
    ports:
      - "8080:80"
   

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: prestashop_db
      MYSQL_USER: prestashop_user
      MYSQL_PASSWORD: prestashop_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: prestashop_user
      PMA_PASSWORD: prestashop_password
    ports:
      - "8181:80"
