version: '3'

services:
  mysql:
    container_name: some-mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
    volumes:
      - dbdata:/var/lib/mysql

  prestashop:
    container_name: prestashop
    image: #kanyawitd/prestag04:SEG04
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      DB_SERVER: some-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
    networks:
      - prestashop_network
    volumes:
      - ./app/controllers:/var/www/html/controllers # To develop controller
      - ./app/modules:/var/www/html/modules # To develop module
      - ./app/modules/testModule:/var/www/html/modules/testModule # To develop module
      - ./app/themes/classic:/var/www/html/themes/classic # To develop theme
      - ./app/img:/var/www/html/img # To store image dat
      - ./app/pdf:/var/www/html/pdf # To adjust pdf generator
      - ./app/classes/:/var/www/html/classes # To develop classes
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    networks:
      - prestashop_network
    environment:
      PMA_HOST: some-mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - 8082:80

networks:
  prestashop_network:

volumes:
  psdata:
  dbdata: