name: Setup PrestaShop Environment
description: Setup a docker Environment for PrestaShop

inputs:
  # PrestaShop Config inputs
  PHP_VERSION:
    required: true
    description: PHP Version For PrestaShop
  ENABLE_SSL:
    required: false
    description: True to Run with SSL
    default: 'true'
  INSTALL_AUTO:
    required: false
    description: True To Auto Install
    default: 'true'
  CP_API_CONFIG:    # Workaround until https://github.com/PrestaShop/PrestaShop/issues/29813 is fixed
    required: false
    description: True To Copy API Config
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: PrestaShop Configuration (Copy of Config API)
      if: inputs.CP_API_CONFIG == 'true'
      shell: bash
      run: cp ./app/config/security_test.yml ./app/config/security_prod.yml

    # Certificate for SSL
    - name: Generate a Certificate
      if: inputs.ENABLE_SSL == 'true'
      shell: bash
      run: |
        ## Install MkCert
          sudo apt install libnss3-tools
          curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/amd64"
          chmod +x mkcert-v*-linux-amd64
          sudo cp mkcert-v*-linux-amd64 /usr/local/bin/mkcert
          ## Generate certificate
          mkcert -key-file ./.docker/ssl.key -cert-file ./.docker/ssl.crt localhost
          ## Link certificate to Chrome Trust Store
          mkdir -p $HOME/.pki/nssdb
          certutil -d $HOME/.pki/nssdb -N
          certutil -d sql:$HOME/.pki/nssdb -n localhost -A -t "TCu,Cu,Tu" -i ./.docker/ssl.crt
          ## Add self-signed certificate to Chrome Trust Store
          mkcert -install

    # Docker to create the shop
    - name: Build and Run shop with docker
      shell: bash
      env:
        PS_ENABLE_SSL: ${{ (inputs.ENABLE_SSL == 'true') && '1' || '0' }}
        PS_INSTALL_AUTO: ${{ (inputs.INSTALL_AUTO == 'true') && '1' || '0' }}
        VERSION: ${{ inputs.PHP_VERSION }}-apache
        URL_FO: ${{ (inputs.ENABLE_SSL == 'false') && 'http://localhost:8001/' || 'https://localhost:8002/' }}
        URL_PING: ${{ (inputs.INSTALL_AUTO == 'true') && 'en/' || 'install-dev/' }}
        PS_DOMAIN: ${{ (inputs.ENABLE_SSL == 'false')  && 'localhost:8001' || 'localhost:8002' }}
        PS_DEV_MODE: '0'
        DB_SERVER: 'mysql'
        DB_NAME: 'prestashop'
        DB_PREFIX: 'tst_'
        DB_USER: 'root'
        DB_PASSWD: 'prestashop'
        PS_LANGUAGE: 'en'
        ADMIN_PASSWD: 'Correct Horse Battery Staple'
      run: |
        USER_ID=$(id -u) GROUP_ID=$(id -g) \
        docker-compose -f docker-compose.yml up -d --build
        bash -c 'while [[ "$(curl -L -s -o /dev/null -w %{http_code} ${{ env.URL_FO }}${{ env.URL_PING }})" != "200" ]]; do sleep 5; done'
