<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV20pn3d\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV20pn3d/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerV20pn3d.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerV20pn3d\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerV20pn3d\appAppKernelProdContainer([
    'container.build_hash' => 'V20pn3d',
    'container.build_id' => '5f30836e',
    'container.build_time' => 1707811285,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV20pn3d');
