app:
  # The main bundle is PrestaShopCoreBundle which will load other dependencies.
  resource: "@PrestaShopBundle/Resources/config/routing.yml"

test:
  resource: "../../tests/Resources/config/routes.yml"

app_modules:
  # Declare routing.yml file in modules/module-name/config folder.
  # v1: only YAML format is supported for now.
  resource: .
  type: module
