# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
  enable_authenticator_manager: true
  password_hashers:
    # auto hasher with default options for the User class (and children)
    PrestaShopBundle\Entity\ApiClient: 'auto'

    # auto hasher with custom options for all PasswordAuthenticatedUserInterface instances
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
      algorithm: 'auto'
      cost: 15

    Symfony\Component\Security\Core\User\User: plaintext

  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    in_memory:
      memory: ~
    admin:
      id: prestashop.security.admin.provider

  firewalls:
    # disables authentication for assets and the profiler, adapt it according to your needs
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    api_token:
      pattern: ^/api/oauth2/token
      security: false

    api:
      pattern: '^(%api_base_path%)(?!/docs)'
      stateless: true
      custom_authenticators:
        - PrestaShop\PrestaShop\Core\Security\OAuth2\TokenAuthenticator
      request_matcher: PrestaShop\PrestaShop\Core\Security\OAuth2\ApiRequestMatcher

  access_control:
    - { path: ^/, roles: PUBLIC_ACCESS }
