# This file will be removed in next version, do not add any service here
services:
  validator.unique.tinymce_max_length_validator:
    alias: PrestaShopBundle\Form\Validator\Constraints\TinyMceMaxLengthValidator
    deprecated:
      package: PrestaShop\PrestaShop
      version: 9.0
    public: true
