# This file will be removed in next version, do not add any service here
services:
  form.form_builder_modifier:
    alias: PrestaShopBundle\Form\FormBuilderModifier
    deprecated:
      package: PrestaShop\PrestaShop
      version: 9.0
    public: true

  prestashop.multistore_checkbox_enabler:
    alias: 'PrestaShopBundle\Service\Form\MultistoreCheckboxEnabler'
    deprecated:
      package: PrestaShop\PrestaShop
      version: 9.0
    public: true
