# This file will be removed in next version, do not add any service here
services:
  prestashop.bundle.form.data_transformer.string_array_to_integer_array:
    alias: 'PrestaShopBundle\Form\DataTransformer\StringArrayToIntegerArrayDataTransformer'
    deprecated:
      package: PrestaShop\PrestaShop
      version: 9.0
    public: true

  prestashop.bundle.form.data_transformer.default_language_to_filled_array:
    alias: 'PrestaShopBundle\Form\DataTransformer\DefaultLanguageToFilledArrayDataTransformer'
    deprecated:
      package: PrestaShop\PrestaShop
      version: 9.0
    public: true

  prestashop.bundle.form.data_transformer.arabic_to_latin_digit:
    alias: 'PrestaShopBundle\Form\DataTransformer\ArabicToLatinDigitDataTransformer'
    deprecated:
      package: PrestaShop\PrestaShop
      version: 9.0
    public: true

  prestashop.bundle.form.data_transformer.idn_converter:
    alias: 'PrestaShopBundle\Form\DataTransformer\IDNConverterDataTransformer'
    deprecated:
      package: PrestaShop\PrestaShop
      version: 9.0
    public: true
