services:
  _defaults:
    autowire: true
    autoconfigure: true
  _instanceof:
    PrestaShop\PrestaShop\Core\FeatureFlag\TypeLayerInterface:
      tags: [ 'PrestaShop\PrestaShop\Core\FeatureFlag\TypeLayerInterface' ]

  PrestaShop\PrestaShop\Core\FeatureFlag\FeatureFlagStateCheckerInterface:
    alias: PrestaShop\PrestaShop\Core\FeatureFlag\FeatureFlagManager
    public: true

  # Feature flag are used to change some behaviour dynamically so they should be lazy by default so that the services are only
  # initialized at the last moment, especially since they are also used in Frontend
  PrestaShop\PrestaShop\Core\FeatureFlag\FeatureFlagManager:
    lazy: true
  PrestaShop\PrestaShop\Core\FeatureFlag\Layer\EnvLayer:
    lazy: true
  PrestaShop\PrestaShop\Core\FeatureFlag\Layer\DbLayer:
    lazy: true
  PrestaShop\PrestaShop\Core\FeatureFlag\Layer\DotEnvLayer:
    arguments:
      $rootDir: !php/const _PS_ROOT_DIR_
    lazy: true
  PrestaShop\PrestaShop\Core\FeatureFlag\Layer\QueryLayer:
    lazy: true
