services:
  _defaults:
    public: false

  PrestaShop\PrestaShop\Core\Foundation\Version:
    arguments:
      - !php/const PrestaShop\PrestaShop\Core\Version::VERSION
      - !php/const PrestaShop\PrestaShop\Core\Version::MAJOR_VERSION_STRING
      - !php/const PrestaShop\PrestaShop\Core\Version::MAJOR_VERSION
      - !php/const PrestaShop\PrestaShop\Core\Version::MINOR_VERSION
      - !php/const PrestaShop\PrestaShop\Core\Version::RELEASE_VERSION

  prestashop.core.foundation.version:
    alias: PrestaShop\PrestaShop\Core\Foundation\Version
    public: true
    deprecated:
      package: PrestaShop\PrestaShop
      version: 9.0
